In [1]:
import tensorflow as tf
print("Tensorflow Version:",  tf.__version__)

Tensorflow Version: 2.15.0


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255, x_test/255

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28,28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)

    ]
)

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.02862341,  0.8998022 ,  0.13721009,  0.44059336, -0.65042305,
        -0.07464269,  0.2984657 ,  0.24436626,  0.53719866,  0.04546688]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07496111, 0.18969072, 0.08848233, 0.11984343, 0.0402524 ,
        0.07158962, 0.10396542, 0.0984904 , 0.13199861, 0.08072592]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.636805

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 4ms/step - loss: 0.2972 - accuracy: 0.9131
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1446 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1079 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0889 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0757 - accuracy: 0.9757


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0748 - accuracy: 0.9779 - 1s/epoch - 3ms/step


[0.0748382955789566, 0.9779000282287598]

In [11]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:2])

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[1.0989982e-07, 1.1989324e-07, 8.5951624e-06, 6.7223969e-05,
        5.8219395e-11, 3.6972686e-08, 6.1704846e-14, 9.9991643e-01,
        2.7103366e-07, 7.2365197e-06],
       [5.3031176e-08, 3.2166694e-04, 9.9963784e-01, 4.0322899e-05,
        4.2141064e-17, 4.9998572e-08, 1.1260272e-09, 2.4953560e-14,
        9.2013899e-08, 4.0621784e-13]], dtype=float32)>